### PR TITLE
Update PyKE version

### PR DESCRIPTION
**Pull request by mirca**
This PR updates the PyKE package version to reflect its latest release.

Let me know if anything else is necessary.

Thanks for the assistance, @jehturner.

cc @barentsen

### CODE REVIEW

**Comment by jehturner** [comment]
Thanks! Would you mind explaining the matplotlib 1.5.3 requirement, please? That might be problematic if other software in the same env requires a different version (or people just want to keep a key package up to date). I'll need to get @jhunkeler's input on that, as the person leading the integration of Astroconda packages. Can it not be dealt with by a slightly looser requirement, such as ">= 1.5.3"?

**Comment by mirca** [comment]
@jehturner We have fixed that! Thanks!

**Comment by jehturner** [comment]
This looks good, as far as I can tell without really testing the functionality (at least the package now loads in pyraf), except for the following caveats:

- Since there's Python source, we should add "python" as both a build- and run-time dependency (sorry, not sure why I didn't have that, but obviously most IRAF packages don't.)

- It appears that your source code only works with Python 2, so I have not made any conda packages for Python 3. It looked like the parsing errors were mostly due to old print syntax though, so it might be easy to make it Python 3 compatible too? (FYI, I _think_ STScI's recommendation that IRAF users should prefer Python 2.7 is mostly based on some Python code in STSDAS etc. not being Python 3 compatible, rather than anything fundamentally not working.)

**Comment by jehturner** [comment]
You can find some conda package builds for Python 2.7 here: http://astroconda.gemini.edu/public (or at http://ssb.stsci.edu/gemini-mirror). It would be great if you could install this package and confirm that you're happy with it:
```
conda config --add channels http://astroconda.gemini.edu/public
source activate your_iraf_env
conda install pyraf.kepler
```

**Comment by jehturner** [comment]
This builds and loads now (and has had at least as much scrutiny as other non-Gemini/STScI packages), so I'll get on and merge it. In any case, it won't get distributed widely until @jhunkeler moves the builds to the main astroconda channel, along with the other new IRAF packages. Please open a new PR if you update your source for Python 3 compatibility.

**Comment by mirca** [comment]
@jehturner Awesome, thank you! For now, we plan to support python2.7 only!

**Comment by jehturner** [comment]
OK. I'll need to figure out how to deal with that in pyraf-all (and reinstate that meta-package, which currently only has pyraf and pyraf.kepler). I think I can just add a condition like [py27] in meta.yaml.

**Comment by mirca** [comment]
@jehturner I'm happy with the package in http://astroconda.gemini.edu/public
Thanks!

**Comment by jehturner** [comment]
Thanks for confirming that.

BTW, when loading the package it complains "Warning: `kepler.keparith' is a task redefinition", since that line appears twice in kepler.cl. That may be worth fixing the next time you update something.

**Comment by mirca** [comment]
@jehturner oh, nice catch, thanks!

**Comment by mirca** [comment]
@jehturner Hi, I wonder when the ``astroconda-iraf`` would be updated so that users won't need to add ``http://astroconda.gemini.edu/public`` in order to get the new version of ``pyraf.kepler``. We would like to start advertising it!
Thanks!

**Comment by jehturner** [comment]
That's a good question, but I don't know the answer and will have to defer to our colleagues at STScI (we are also in the same position).

**Comment by jehturner** [comment]
The new packages have just gone live at http://ssb.stsci.edu/astroconda (sorry there wasn't more notice, but this was only confirmed about a day ago).

**Comment by mirca** [comment]
Great to hear that!!
Thank you very much, @jehturner!

**Pull request merged**
